Repository Premiurly/polkassembly, pull requests merged in 2022-11, with the labels that each got.

#240 fix: post width expand when there is no governance sidebar
  front-end/src/components/Post/Post.tsx
Labels: bug

#247 fix/listing card
  front-end/src/components/GovernanceCard.tsx
  front-end/src/ui-components/OnchainCreationLabel.tsx
  front-end/src/ui-components/StatusTag.tsx
  front-end/src/ui-components/TopicTag.tsx
Labels: bug

#228 [WIP] gov2 referendum tasks
  chain-db-open-server/prisma/datamodel.prisma
  chain-db-open-server/src/generated/prisma-client/index.ts
  chain-db-open-server/src/generated/prisma-client/prisma-schema.ts
  chain-db-open-server/src/generated/prisma.graphql
  chain-db-open-server/src/index.ts
  chain-db-open-server/src/resolvers/query.ts
  chain-db-open-server/src/resolvers/subscription.ts
  chain-db-open-server/src/schema.graphql
  chain-db-watcher/src/generated/chain-db-graphql.ts
  chain-db-watcher/src/generated/discussion-db-graphql.ts
  chain-db-watcher/src/graphql_helpers.ts
  chain-db-watcher/src/index.ts
  chain-db-watcher/src/queries.ts
  chain-db-watcher/src/queries/discussions-db.queries.ts
  chain-db-watcher/src/sync/getter.ts
  chain-db-watcher/src/sync/index.ts
  chain-db-watcher/src/sync/queries/chain-db.queries.ts
  chain-db-watcher/src/sync/queries/discussions-db.queries.ts
  chain-db-watcher/src/sync/utils.ts
  chain-db-watcher/src/types.ts
  front-end/src/generated/graphql.tsx
  front-end/src/gov2/queries.ts
  hasura/hasura-migrations/metadata/tables.yaml
  hasura/hasura-migrations/migrations/1668258338117_alter_table_public_onchain_links_add_column_onchain_referendumv2_id/down.sql
  hasura/hasura-migrations/migrations/1668258338117_alter_table_public_onchain_links_add_column_onchain_referendumv2_id/up.sql
  hasura/hasura-migrations/migrations/1668258355967_alter_table_public_onchain_links_add_column_track/down.sql
  hasura/hasura-migrations/migrations/1668258355967_alter_table_public_onchain_links_add_column_track/up.sql
  hasura/hasura-migrations/migrations/1668258451894_alter_table_public_onchain_links_add_column_onchain_referendumv2_status/down.sql
  hasura/hasura-migrations/migrations/1668258451894_alter_table_public_onchain_links_add_column_onchain_referendumv2_status/up.sql
  hasura/hasura-migrations/migrations/1668258499553_alter_table_public_onchain_links_add_column_origin/down.sql
  hasura/hasura-migrations/migrations/1668258499553_alter_table_public_onchain_links_add_column_origin/up.sql
  hasura/hasura-migrations/migrations/1668264057338_create_table_public_track_info/down.sql
  hasura/hasura-migrations/migrations/1668264057338_create_table_public_track_info/up.sql
  node-watcher/datamodel.prisma
  node-watcher/package.json
  node-watcher/src/generated/prisma-client/index.ts
  node-watcher/src/generated/prisma-client/prisma-schema.ts
  node-watcher/src/tasks/createPreimageV2.ts
  node-watcher/src/tasks/createReferendumStatusV2.ts
  node-watcher/src/tasks/createReferendumV2.ts
  node-watcher/src/tasks/index.ts
  node-watcher/src/tasks/types.ts
  node-watcher/src/util/statuses.ts
  node-watcher/yarn.lock
Labels: do not merge

#246 feat/comments timeline
  front-end/src/components/Post/Comment/Comment.tsx
  front-end/src/components/Post/Comment/Comments.tsx
  front-end/src/components/Post/PostCommentForm.tsx
  front-end/src/components/Post/Tabs/PostDescription.tsx
Labels: enhancement

#273 fix: editor header only show when user is typing
  front-end/src/ui-components/MarkdownEditor.tsx
Labels: enhancement

#277 Fix/text editor position
  front-end/src/components/Post/Tabs/PostDescription.tsx
Labels: bug

#287 fix(Sidebar): removing list-style
  front-end/src/components/AppLayout/index.tsx
Labels: bug
